const BASE = "https://prushak.store"
export const PRODUCT_INDEX = BASE+"/api/index"
export const PRODUCT_DESTROY = BASE+"/api/destroy"
export const PRODUCT_STORE = BASE+"/api/store"
export const PRODUCT_DUBLICATE = BASE+"/api/dublicate"
